# PYTHON STRINGS

In [72]:
x='hello world'
x.count('e')
x.upper()
x.replace('a','s')

x[6:-2]
x[1:len(x):2]
x[len(x):6:-2]
x=[1,2,1,2]
x.remove(2)
#print(x.remove(2))
del x[1]
concat=x+[1,2,3]
print(concat)
5 in concat
t="hola soy joaco".split()
print (type(t))
print ("hola soy joaco")
print(list("hola soy joaco"))
print(list("hola soy joaco".split()))
 

[1, 2, 1, 2, 3]
<class 'list'>
hola soy joaco
['h', 'o', 'l', 'a', ' ', 's', 'o', 'y', ' ', 'j', 'o', 'a', 'c', 'o']
['hola', 'soy', 'joaco']


# PYTHON LIST

In [101]:
import random as r
#help(r)
l=list()

for i in range(10):
    cost=r.randint(100,500)
    coin=r.randint(0,2)
    pair=coin,cost
    l.append(pair)
for coin,cost in l:
    a=0
    #print ((coin,cost))

set_=set(l)
print(len(set_) == len(l))
print(set_)
set1={1,12,1,23,13,13,1212,1,12,2,3}
set2=set([r.randint(1,3) for _ in range(10)])
print(set1 == set2)
print(set1.union(set2))
print(set1.intersection(set2))
print(set2.issubset(set1))

True
{(0, 412), (2, 287), (1, 442), (2, 227), (2, 437), (2, 398), (1, 267), (2, 311), (1, 347), (1, 379)}
False
{1, 2, 3, 12, 13, 23, 1212}
{1, 2, 3}
True


# PYTHON DICTIONARIES

In [19]:
dict1={'key1':1, 'key2':2, 'key3':4, 'key4':8}
print(dict1)
print(dict1['key3'])
values=dict1.values()
print(list(values))
dict1.keys()
for x in dict1.keys():
    print(x)
print(len(dict1))

{'key1': 1, 'key2': 2, 'key3': 4, 'key4': 8}
4
[1, 2, 4, 8]
key1
key2
key3
key4
4


In [45]:
school_dict:dict={}
school_dict['Salta']='verbum'
school_dict['Buenos Aires']='uba'
 
list_tuples=[(1,2),(5,10),(2,1),(3,4)]
list_list=[[1,2],[4,10],[2,1],[3,4]]
list_tuples=dict(list_tuples)
list_list=dict(list_list)
'Salta'in school_dict
'uba' in school_dict
list(list_list)
print(list(list_tuples))
list(school_dict)

[1, 5, 2, 3]


['Salta', 'Buenos Aires']

# NUMPY ARRAYS


In [2]:
import numpy as np
x=np.array([1,1,2]) 
y=np.array([[1,1,2],
            [6,24,120]])
x.shape
x.size 
y.shape
y.size

6

In [76]:
print(np.arange(1,10,1))
print(np.arange(2,8,2))
print(np.arange(2,4,0.5))
print(np.arange(0,3+1/3,1/3))

[1 2 3 4 5 6 7 8 9]
[2 4 6]
[2.  2.5 3.  3.5]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333]


In [33]:
x=np.linspace(1,3,10)
print (x)
x[-1::-1]
x[5:]

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


array([2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [48]:
y[0,:]
y[1,-1]
#y[:,[0,2]]

np.int64(120)

In [63]:
z=np.zeros((3,3))
0==z[0,:]
np.ones((2,2))
np.empty(3)

array([2.11111111, 1.88888889, 1.66666667])

In [80]:
a=np.arange(1,7,1)
a[3]=7
a[:3]=[10,9,8]
a[2:4]=0
print(a)

[10  9  0  0  5  6]


In [96]:
a=np.array([ np.arange(1,3,1), np.arange(3,5,1) ])
a+2==2+a
a*2==2*a
a**2
a/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [100]:
b=np.array([ np.arange(1,2,0.5), np.arange(3,4,0.5) ])
a+b
a/b
a*b

array([[ 1.,  3.],
       [ 9., 14.]])

In [105]:
np.sqrt([2,4,8])

array([1.41421356, 2.        , 2.82842712])

In [198]:
x=np.array(np.arange(1,7))
l=[12,12]+[21,21]
a=[i if i>20 else None for i in l]
y=np.array([1,2,3,0,2,3])
boolean_np=x>y
a=y[[True if i % 2 == 0 else False for i in range(6)]]
print(y[y>2])
print(a)
#y?


[3 3]
[1 3 2]


## ex 4 5 

In [143]:
from math import sin as s
from math import cos as c
x=10;y=3
u=x+y;   v=x*y;   w=x/y
z=s(x);   r=8*z;   s=5*s(x*y)
p=x**y
%whos

S="123"
print(float(S)) 

Variable     Type                          Data/Info
----------------------------------------------------
S            str                           123
a            ndarray                       3: 3 elems, type `int64`, 24 bytes
b            ndarray                       2x2: 4 elems, type `float64`, 32 bytes
boolean_np   ndarray                       6: 6 elems, type `bool`, 6 bytes
c            builtin_function_or_method    <built-in function cos>
l            list                          n=4
math         module                        <module 'math' from '/hom<...>313-x86_64-linux-gnu.so'>
np           module                        <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
p            int                           1000
r            float                         -4.352168887114958
s            float                         -4.940158120464309
u            int                           13
v            int                           30
w            float                 

## ex 8 - 13

In [154]:
'python' in 'python is great'
'python is great'[10:]
a=[1,23,1,31,2,31,321]
a.sort(reverse=False)
print(a)
t=1,2
t[1]


[1, 1, 2, 23, 31, 31, 321]


2

## ex 17

In [187]:
dict2={
    'A':'a',
    'B':'b',
    'C':'c',
}
dict2['C']
'C'in dict2.keys()
np.linspace(-10,10,100)
ar_a=np.arange(-5,5)
print(ar_a[ar_a>0])
y=np.array( [ [1,1,2],[5,14,42],[429,1430,4862] ] )
y.T
z=np.zeros((3,5))
z[:,1]=1 
z

[1 2 3 4]


array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])