# GOOG PRACTICE PROGRAMMING

## PLANNING
## COMMENTING
## TESTING
## DEBUGGING
## FROM TOP -> BOTTOM, FROM BOTTOM -> TOP

# READING WRITING .TXT

In [12]:
f = open('test.txt','w')
n = 4
for i in range(n):
    f.write(f'Linea {i}. \n')
f.close()

SyntaxError: unterminated string literal (detected at line 2) (2575870646.py, line 2)

In [15]:
f = open('test.txt','a')
# append an line/string to the file
f.write('Last Line.')
f.close()

In [17]:
f = open('test.txt','r')
content = f.read()
f.close()
print ( content )

Linea 0 
Linea 1 
Linea 2 
Linea 3 
Last Line.


In [18]:
f = open('test.txt','r')
content = f.readlines()
f.close()
print ( content )

['Linea 0 \n', 'Linea 1 \n', 'Linea 2 \n', 'Linea 3 \n', 'Last Line.']


In [20]:
import numpy as np
arr = np.array( [ [1.20, 3.21, 2.41],[2.31, 2.15, 3.23] ] )
np.savetxt( 'my_arr.txt', arr, fmt = '%.2f', header = 'COL 1 COL 2 COL 3' )

In [21]:
arr2 = np.loadtxt('my_arr.txt')
print ( arr2 )

[[1.2  3.21 2.41]
 [2.31 2.15 3.23]]


In [ ]:
n = 5
f = open()
for i in range ( n ):
    np.random.rand(5)

# READING WRITING .CSV

In [2]:
import numpy as np
data = np.random.rand(100,5)
#np.savetxt?
np.savetxt( 'my_csv.csv', data, fmt = '%.2f',  delimiter = ',', header = 'Col 1 Col 2 Col 3 Col 4 Col 5')

In [54]:
#np.loadtxt?
data = np.loadtxt('my_csv.csv', delimiter = ',')
print ( data[ :5, [0,1,2,3,4] ])

[[0.42 0.07 0.2  0.09 0.02]
 [0.18 0.15 0.33 0.61 0.77]
 [0.82 0.93 0.44 0.74 0.9 ]
 [0.41 0.56 0.25 0.33 0.74]
 [0.43 0.81 0.45 0.77 0.65]]


In [4]:
data = np.savetxt( 'my_text_data_into_cvs.cvs', np.loadtxt('my_arr.txt'),
                   delimiter = ',', fmt = '%.2f', header = 'Col 1 Col 2 Col 3 Col4' )


In [12]:
np.savetxt( 'data/random_data3.csv', np.random.random( (20,4) ), 
            delimiter = ';', fmt = '%.3f', 
            header = 'Col1, Col2, Col3, Col4' )

In [14]:
data_3 = np.loadtxt( 'data/random_data3.csv', delimiter = ';' )
print( data_3 )

[[0.168 0.617 0.795 0.947]
 [0.965 0.558 0.902 0.952]
 [0.843 0.992 0.612 0.32 ]
 [0.74  0.485 0.333 0.243]
 [0.104 0.316 0.68  0.65 ]
 [0.082 0.725 0.736 0.794]
 [0.775 0.133 0.353 0.731]
 [0.323 0.852 0.54  0.201]
 [0.148 0.81  0.089 0.558]
 [0.27  0.253 0.46  0.636]
 [0.071 0.217 0.567 0.011]
 [0.948 0.431 0.796 0.431]
 [0.488 0.93  0.82  0.907]
 [0.661 0.661 0.316 0.774]
 [0.792 0.35  0.366 0.41 ]
 [0.951 0.324 0.427 0.292]
 [0.06  0.418 0.208 0.599]
 [0.839 0.873 0.569 0.727]
 [0.67  0.085 0.925 0.548]
 [0.642 0.994 0.662 0.053]]


# PÍCKLES FILES

In [69]:
import pickle
dict_a = {'A': 0, 'B': 1, 'C': 2}

#pickle.dump?
pickle.dump( dict_a, open('my_dict.pkl','wb') )

In [70]:
#pickle.?
dict_data = pickle.load( open( 'my_dict.pkl', 'rb' ) )
print( dict_data )

{'A': 0, 'B': 1, 'C': 2}


In [16]:
import pickle 
pickle.dump( np.loadtxt('data/random_data3.csv', delimiter = ';'), 
             open('data/my_random_data3.pkl', 'wb')             )

In [18]:
data_3 = pickle.load( open('data/my_random_data3.pkl', 'rb') )
print( data_3 )

[[0.168 0.617 0.795 0.947]
 [0.965 0.558 0.902 0.952]
 [0.843 0.992 0.612 0.32 ]
 [0.74  0.485 0.333 0.243]
 [0.104 0.316 0.68  0.65 ]
 [0.082 0.725 0.736 0.794]
 [0.775 0.133 0.353 0.731]
 [0.323 0.852 0.54  0.201]
 [0.148 0.81  0.089 0.558]
 [0.27  0.253 0.46  0.636]
 [0.071 0.217 0.567 0.011]
 [0.948 0.431 0.796 0.431]
 [0.488 0.93  0.82  0.907]
 [0.661 0.661 0.316 0.774]
 [0.792 0.35  0.366 0.41 ]
 [0.951 0.324 0.427 0.292]
 [0.06  0.418 0.208 0.599]
 [0.839 0.873 0.569 0.727]
 [0.67  0.085 0.925 0.548]
 [0.642 0.994 0.662 0.053]]


# .JSON FILES

In [19]:
import json

In [73]:
import json
school = {
    'escuela': 'verbum',
    'direccion': {
        'provincia': 'salta',
        'ciudad': 'capital',
        'postal': '4400',
    }
    ,
    'alumnos': [
        'Bauti',
        'Juli',
        'Coni'
    ]
    ,
    'array': [1,2,3]
}
json.dump(school, open('school.json','w'))
#json.dump?

In [77]:
school_data = json.load(open('school.json','r'))
type(school_data)

dict

In [20]:
graph = {
    '0': [1,2,3],
    '1': [4,2],
    '2': [1],
    '3': [0],
    '4': [1,2,3]
}
json.dump( my_graph, open( 'data/my_graph.json','w' ) )

In [21]:
my_graph = json.load( open('data/my_graph.json', 'r') )
print( my_graph )

{'0': [1, 2, 3], '1': [4, 2], '2': [1], '3': [0], '4': [1, 2, 3]}


In [34]:
data_set = {
    'data': [1,2,3]
}
json.dump( data_set, open( 'data/my_data_set.json','w' ) )

In [36]:
my_data = json.load( open( 'data/my_data_set.json', 'r' ) )
print (my_data['data'])

[1, 2, 3]


# HIERARCHICAL DATA FORMAT (HDF5)